### ISSUE TITLE
Can't get it to start

### ISSUE THREAD

**Issue by mgutier9** [skyfriends/drum-machine#30]
I am not able to get the app to start. Is there anything that I need to do in order to get it to work? I cloned it and ran npm install, npm start, but it gives me errors about the script

**Comment by JacobMGEvans** [comment]
I'll take a look later today.

**Comment by JacobMGEvans** [comment]
And I forgot...sorry.

**Comment by JacobMGEvans** [comment]
Can you give me the steps you used to try and start the app @mgutier9 ?

**Comment by mgutier9** [comment]
No problem thank you for taking the time to look into it!
I'm using visual studio code and github desktop.
1. Cloned repo
2. CD into directory
3. CD into React Folder 
4. NPM install
5. Npm start
After that I get the error. I did try to npm install in the root directory but that doesn't seem to do anything.

**Comment by JacobMGEvans** [comment]
Yeah so you probably need to npm install on the root directory

remove their yarn.lock if you are using NPM in the React directory and `npm install` again then try running 
`npm run start` in one terminal
open up another terminal and do
`npm run watch` in the second terminal

This is a fullstack application so just running the frontend and not the server won't likely do any good.

**Comment by mgutier9** [comment]
I'll try that as soon as I am able and let you know

**Comment by JacobMGEvans** [comment]
If it doesnt work I will clone locally and debug further. This is just my current speculation looking at the project and the steps you gave me 😄 .

**Comment by mgutier9** [comment]
So after following your instructions, npm run start is not working on root directory. npm run watch (on react directory) does work and is running on part 1234, and when you follow the link it gives you a blank screen with "tada" as the tab name.

**Comment by JacobMGEvans** [comment]
I didnt say run npm start on the root directory. 
**remove their yarn.lock if you are using NPM in the React directory and npm install again then try running
npm run start in one terminal
open up another terminal and do
npm run watch in the second terminal**
This was all in the React Directory, I said to run `npm install` in the root

**Comment by JacobMGEvans** [comment]
If you look in the package.json you can see the script commands available. 

in the root, the package.json doesn't have a script command available

**Comment by mgutier9** [comment]
The npm run start does not work on the react directory either:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle FRONT@1.0.0~prestart: FRONT@1.0.0
6 info lifecycle FRONT@1.0.0~start: FRONT@1.0.0
7 verbose lifecycle FRONT@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle FRONT@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-9 verbose lifecycle FRONT@1.0.0~start: CWD: C:\Users\Martin\Documents\GitHub\Banana-Beat\react
10 silly lifecycle FRONT@1.0.0~start: Args: [ '/d /s /c', 'node index.js' ]
11 silly lifecycle FRONT@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle FRONT@1.0.0~start: Failed to exec start script
13 verbose stack Error: FRONT@1.0.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid FRONT@1.0.0
15 verbose cwd C:\Users\Martin\Documents\GitHub\Banana-Beat\react
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v12.18.2
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error FRONT@1.0.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the FRONT@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by JacobMGEvans** [comment]
Hmm, I will have to clone it and try a few things. To be fair its a 3-year-old project from a code Bootcamp lol
